"""
https://leetcode.com/problems/find-the-difference

Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.
"""
from collections import Counter
from itertools import chain





def find_the_difference(s, t):
    """
    :type s: str
    :type t: str
    :rtype: str
    """
    s_hash = Counter(s)
    t_hash = Counter(t)
    t_hash.subtract(s_hash)
    for i in chain(t_hash.elements()):
        return i

if __name__ == "__main__":
    print("""
    Input:
    s = "abcd"
    t = "abcde"
    
    Output:
    e
    
    Explanation:
    'e' is the letter that was added.
    """)

    print(find_the_difference('abcd', 'abcde'))

